### PR TITLE
Fix element selectors fix #368

### LINKED ISSUE #368: Fetch more messages does not work with multiple chat windows
## Describe the bug

It is not possible to have multiple chat windows on the same page.
When there are multiple chat windows and you scroll up to the fetch more messages, only the first chat window will fetch new messages and will also trigger this event on the second chat window. 
In the second chat window there will be no fetch more messages event when you scroll up.

We are using the chat component in multiple popup windows to communicate with multiple users at the same time.

## Steps to reproduce

 1. Go to https://playcode.io/vac_multi_chats
 2. Scroll up the second chat window with the name `Room 11` and no messages will be fetched
 3. Scroll up the first chat windows `Room 10`
 5. See that  `Room 10` and `Room 11` will fetch new messages

## Expected behavior

Each chat component should behave independent

## Screenshots

Here is an example of our website:
grafik

## Device (please complete the following information)

- OS: Windows 11
- Browser: Firefox 105, Chrome 106
- Package version: 2.03

### PR DESCRIPTION
**Pull request by NINI1988**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
fixes #368
- [ ] All tests are passing

### CODE REVIEW

**Comment by NINI1988** [comment]
My Firefox says, that property bottom has no affect on that element, because it's static or something like that. Maybe I missed something, but have you tried it?

**Comment by antoine92190** [comment]
Yes I have tried it and it breaks the emoji / tags / templates UI

**Comment by NINI1988** [comment]
I have disabled the file upload in my application, maybe that's the difference. Without an image it works as expected. I will fix it when I have time.

**Comment by NINI1988** [comment]
It works in firefox and chrome as expected. Which browser do you use and how does it look like?

FilesAndEmojis

**Comment by antoine92190** [comment]
Actually it works, I don't know what happened last time...

**Review by antoine92190 — APPROVED** [review]

**Pull request merged**
