### PR TITLE
Preview image in the full size of Room component when clicking messages with image files.

### PR DESCRIPTION
**Pull request by liweicheng00**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
preview

### CODE REVIEW

**Comment by Alisonispig** [comment]
I think after adding the preview, you can add functions such as the previous picture and the next picture, and even enhance the interface, such as zooming in and out, rotating left and right, just like elementui.https://element.eleme.cn/#/zh- CN/component/image#da-tu-yu-lan Of course, if you are inconvenient, I can also help after the authors merge

**Comment by antoine92190** [comment]
Thanks for the PR!
However, the issue is that developers are loosing the flexibility to implement their own implementation when clicking on the image. We should probably add a prop to disable this behaviour, something like `media-modal-preview: true/false`

**Comment by liweicheng00** [comment]
I had added  prop to disable this behavior and change some variable name for more readable. I am not sure if I need to resolve the conflicts before I commit again.

**Comment by liweicheng00** [comment]
> I think after adding the preview, you can add functions such as the previous picture and the next picture, and even enhance the interface, such as zooming in and out, rotating left and right, just like elementui.https://element.eleme.cn/#/zh-CN/component/image#da-tu-yu-lan Of course, if you are inconvenient, I can also help after the authors merge

This feature sounds great and I think it is not complex. I will see if I have time for doing this after author merge.

**Comment by antoine92190** [comment]
Yes please resolve the conflicts otherwise I won’t be able to merge this PR

**Comment by antoine92190** [comment]
I tested the branch locally, it works fine and the idea is good, but the UI is not very beautiful. I'll improve it a bit before we can merge this.

**Pull request merged**
