### PR TITLE
Fix: Header size and scrollarea margin fix #369

### LINKED ISSUE #369: Room Header size and scrollarea margin
## Describe the bug

The sizes of the header and the margin-top of the messages scroll area does not fit.
This causes the scroll up button to disappear half.

https://github.com/antoine92190/vue-advanced-chat/blob/472563d4882ea873c69f5f8ee739eee90b673228/src/lib/Room/RoomHeader/RoomHeader.scss#L5

https://github.com/antoine92190/vue-advanced-chat/blob/839359228416e1d9e51ce3d7e27c5904be5f1918/src/lib/Room/Room.scss#L36

It should be replaced by: `margin-top: 65px;`

## Steps to reproduce

 1. Go to https://antoine92190.github.io/vue-advanced-chat/
 3. Open chat 

## Expected behavior

The scrollbar should be completely visible

## Screenshots

image

## Device (please complete the following information)

- OS: Windows 10
- Browser: Chrome 105.0.5195.127
- Package version: 2.0.3

### PR DESCRIPTION
**Pull request by NINI1988**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**The PR fulfills these requirements:**

Closes #369 
- [ ] All tests are passing

### CODE REVIEW

**Comment by antoine92190** [comment]
Thanks for the PR!
Just a question, why 65px and not 64px?
Also, have you tested that it’s not breaking emoji / templates / user tags suggestions display?

**Comment by NINI1988** [comment]
There is a one pixel border below the header.

And for smaller screen, maybe there must be also a margin of 51px?
https://github.com/antoine92190/vue-advanced-chat/blob/472563d4882ea873c69f5f8ee739eee90b673228/src/lib/Room/RoomHeader/RoomHeader.scss#L106-L107

https://github.com/antoine92190/vue-advanced-chat/blob/839359228416e1d9e51ce3d7e27c5904be5f1918/src/lib/Room/Room.scss#L88-L91

There is no differences for emoji, user tags and template suggestions.

**Comment by NINI1988** [comment]
When `position: absolute` is removed from `.vac-room-header` we don't need to set margin-top at all?
Or is there another dependency?

**Comment by antoine92190** [comment]
For 51px you may be right, you can test and fix it if necessary. We can also probably remove the margin when header position is changed, you can test that as well. I’m currently in holidays so I will only be able to have a deeper look in a couple weeks

**Pull request merged**
