### PR TITLE
fix #260 - Updated to use shadowRoot rather than document.querySelector for registering event listeners on th eemojipicker component

### LINKED ISSUE #260: Angular compatibility issues
## Describe the bug
In using the component within an Angular application I came across an issue when clicking on the emoji icon/button the following error is thrown: `Cannot read properties of null (reading 'addEventListener')`.  While this still does open the panel with all the emojis in it, clicking on an emoji does nothing.

## Steps to reproduce
To reproduce this issue simply import the `vue-advanced-chat` component into an angular application, initialise the chat window and click on the emoji icon/button next to the textarea in which to type a message.

## Expected behavior
The expected behaviour would be to show with list of emojis without any errors thrown and when clicking on a single emoji to use, the emoji is displayed in the textarea where a message may be typed.

## Screenshots

image

### PR DESCRIPTION
**Pull request by rajeev-ayer**
…the emoji-picker component to add event listener.

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by antoine92190** [comment]
Looks good, but why do you need to update .gitignore?

**Comment by rajeev-ayer** [comment]
> Looks good, but why do you need to update .gitignore?

My apologies.  That shouldn't have gone through.  I had created an IDE workspace on my machine and added the workspace settings file to .gitignore.

**Comment by antoine92190** [comment]
@rajeev-ayer Could you the `.gitignore` file so I can merge this?

**Comment by rajeev-ayer** [comment]
> @rajeev-ayer Could you revert the `.gitignore` file so I can merge this?

All done @antoine92190.

**Comment by antoine92190** [comment]
Thanks!

**Pull request merged**
