### PR TITLE
fix #278 implement shiftEnterToSend

### LINKED ISSUE #278: Handle the send message event on Enter key press
When we use to type the message using Japanese text then we get the suggestion dropdown. If we select the option from the dropdown by pressing the enter key then the "send-message" events get triggered. We need some functionality to handle this scenario.

### PR DESCRIPTION
**Pull request by thu-san**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix
- [x] Feature https://github.com/antoine92190/vue-advanced-chat/issues/278
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] All tests are passing

If adding a **new feature**, the PR's description includes:

- [x] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Comment by antoine92190** [comment]
I will test the branch on my side, but in the meantime could you please revert the `dist` files? This is making unnecessary noise on the PR

**Comment by thu-san** [comment]
@antoine92190 
I have reverted `dist` files

**Comment by antoine92190** [comment]
I tested the PR locally and it seems to work fine. I'm just wondering if this [solution](https://github.com/antoine92190/vue-advanced-chat/issues/278#issuecomment-1114257083) would not work? This would me be cleaner if it does. Could you test on your side and let me know?

**Comment by itTkm** [comment]
> I tested the PR locally and it seems to work fine. I'm just wondering if this [solution](https://github.com/antoine92190/vue-advanced-chat/issues/278#issuecomment-1114257083) would not work? This would me be cleaner if it does. Could you test on your side and let me know?

I have tested that [solution](https://github.com/antoine92190/vue-advanced-chat/issues/278#issuecomment-1114257083), but it's not working for me. (Mac + Chrome/Safari)
So I think current changes is best solution for #278.

**Comment by antoine92190** [comment]
Fixed in https://github.com/antoine92190/vue-advanced-chat/pull/309

**Pull request closed without merging**
